- src/adapter.rs
- src/adapter/file_adapter.rs
- src/adapter/memory_adapter.rs
- src/enforcer.rs
- src/errors.rs
- src/internal_api.rs
- src/lib.rs
- src/management_api.rs
- src/rbac_api.rs
`Adapter` is easy to generate error, because of error propagating, `model` and `enforcer` that used those adapter methods must return an error.
I actually don't like this commit because of those annoying `Results`, what do you think? @GopherJ @hsluoyz
> add error handling

- src/adapter/file_adapter.rs
- src/adapter/memory_adapter.rs
- src/enforcer.rs
- src/management_api.rs
- src/model.rs
- src/rbac/default_role_manager.rs
- src/rbac/role_manager.rs
- src/rbac_api.rs
This pull request is originally meant to fix suggestions at https://github.com/casbin/casbin-rs/pull/9 but in later commits I added more rbac apis.
> Optimize role manager and add more rbac apis

- examples/priority_indeterminate_policy.csv
- examples/rbac_model_in_multi_line.conf
- examples/rbac_model_matcher_using_in_op.conf
- examples/rbac_with_domains_policy.csv
- examples/rbac_with_hierarchy_with_domains_policy.csv
- examples/rbac_with_not_deny_model.conf
- examples/rbac_with_pattern_model.conf
- examples/rbac_with_pattern_policy.csv
- src/adapter/memory_adapter.rs
- src/enforcer.rs
- src/model.rs
- src/rbac_api.rs
When using domain model, we need to pass a domain to g function, but sadly `rhai` doesn't support variadic or optional parameters now, so I split a g function into `gg2` and `gg3`, register these 2 functions  into `rhai` so we can handle these 2 cases at runtime.
> make g function support 2 or 3 parameters

- Cargo.toml
- src/effector.rs
- src/enforcer.rs
- src/model.rs
- src/rbac/default_role_manager.rs
- src/rbac/role_manager.rs
- src/rbac_api.rs
The original version uses `Rc`, `RefCell` and `HashMap` which are not shareable between threads.
This commit replaced `Rc` with `Arc`, `RefCell` with `RwLock` and manually deal with locks with `read().unwrap()` and `write().unwrap()`, a simple test `test_role_api_threads` shows how to operate casbin in a thread and then sync to other threads.
> Add multi-thread support

- src/lib.rs
While developing diesel-adapter, I'm having problems creating an error type to be able to be shared/transferred across threads.
I tried:
```rust
unsafe impl Send for MyError {}
unsafe impl Sync for MyError {}
```
but it still cannot work, I would like to release a first version of `diesel-adapter`, can we just remove these two markers at the very early stage and add them in the future?
> remove Send & Sync marker to make it easier to construct error types

- src/adapter/file_adapter.rs
- src/enforcer.rs
- src/model.rs
Try to resolve #5 `Investigate how to parse in operator in config file @GopherJ`
This PR adds an `inMatch` function and a regex to handle `in` operator.
It will convert the following matcher:
```
g(r.sub, p.sub) && r.act in ["a","b","c"] && r.sub in ["alice","bob"] && r.obj in ["data1","data2"]
```
to
```
g(r.sub, p.sub) && inMatch(r.act, ["a","b","c"]) && inMatch(r.sub, ["alice","bob"]) && inMatch(r.obj, ["data1","data2"])
```
The supported `in` operations are:
```
r.sub in ["alice", "bob"]
```
OR
```
r.obj in ("a", "b")
```
> add in operator

- src/model.rs
Hey!
Very cool project, thanks for creating this!
I went through the source to get a better understanding of what's happening under the hood and stumbled over this function `load_assersions` in `model.rs`.
It seems like a minor typo of `assertion` to me, so I renamed it.
If it was named this way intentionally, feel free to discard this change. ☺️
> fix typo in load_assertion

- Cargo.toml
- README.md
- src/adapter/file_adapter.rs
- src/lib.rs
- src/management_api.rs
- src/prelude.rs
- src/rbac_api.rs
This PR fix more rbac apis which don't have domain parameter.
It adds also the prelude module which implements `management api`, `internal api`, `rbac api` etc.
Instead of doing:
```rust
use casbin::{Model, Enforcer, FileAdapter};
use casbin::{RbacApi, MgmtApi, InternalApi};
```
we can now do:
```rust
use casbin::prelude::*;
```
> fix more rbac apis (add missing domain parameter) & add prelude module

- Cargo.toml
- src/adapter/file_adapter.rs
- src/adapter/memory_adapter.rs
- src/management_api.rs
- src/model.rs
- src/rbac_api.rs
Previously we are using `sort_unstable` + `dedup` to avoid adding a policy the second time, but the sort operation is expensive, so I made this PR which stores policies in `HashSet`, in rust there is no problem to compare two arrays.
That'll probably make it more efficient.
> using IndexSet to store policy in assertion

- src/management_api.rs
- src/rbac_api.rs
Fixes #65.
Added the following tests in `management_api.rs`:
- `test_modify_policies_api`
- `test_modify_grouping_policies_api`
For:
```rust
async fn add_policies(&mut self, paramss: Vec<Vec<&str>>) -> Result<bool>;
async fn remove_policies(&mut self, paramss: Vec<Vec<&str>>) -> Result<bool>;
async fn add_named_policies(&mut self, ptype: &str, paramss: Vec<Vec<&str>>) -> Result<bool>;
async fn remove_named_policies(&mut self, ptype: &str, paramss: Vec<Vec<&str>>)
-> Result<bool>;
async fn add_grouping_policies(&mut self, paramss: Vec<Vec<&str>>) -> Result<bool>;
async fn remove_grouping_policies(&mut self, paramss: Vec<Vec<&str>>) -> Result<bool>;
async fn add_named_grouping_policies(
&mut self,
ptype: &str,
paramss: Vec<Vec<&str>>,
) -> Result<bool>;
async fn …
```
> Added Unit Tests for `addPolicies` and `removePolicies`

- src/adapter/file_adapter.rs
- src/config.rs
- src/enforcer.rs
In the `FileAdapter` when the method is unimplemented like `add_policy` instead of returning `Ok(true)` would false be a better signal or even `panic!("this is not available for 'FileAdapter')` maybe?
> remove clones and string allocs, use macro for model retreval

- .travis.yml
- Cargo.toml
- src/adapter/memory_adapter.rs
- src/cached_enforcer.rs
- src/emitter.rs
- src/enforcer.rs
- src/error.rs
- src/model/function_map.rs
This PR
Adds
- Enforcer::get_adapter
- Enforcer::get_mut_adapter
- Enforcer::save_policy  => for periodically calling for saving policies into adapter because auto_save doesn't work for FileAdapter
Improves
- Enforcer::set_model => let it accepts `TryIntoModel` bound
- Enforcer::set_adapter => let it accepts `TryIntoAdapter` bound
- upgrade rhai to 0.11.1 to make sure `casbin::Error` is Send and Sync
> upgrade rhai to 0.11.1 to make Error Send, Sync

- src/enforcer.rs
- src/model/default_model.rs
#78  Because rust doesn't support variadic parameters, we finally decide to use a json string to represent a request object, it can be parsed into a json object and then do evaluation in rhai.
@GopherJ please take a look
@schungx I found `#{}` works in 0.11.1, so no need to upgrade to 0.12.0 right?
> Implement ABAC

- .github/workflows/benchmark.yml
- .github/workflows/rustdoc.yml
Added support for benchmark charts, please enjoy it.
**Usage**:
Need a new GitHub token that can read and write repo, and add it to [secrets](https://github.com/casbin/casbin-rs/settings/secrets/new) as a `PERSONAL_GITHUB_TOKEN`.
May see it at https://casbin.github.io/casbin-rs/dev/bench
**Example**:
See Online Example -> https://psiace.me/loge/dev/bench/
**FAQ**
Why change `force_orphan: true` to `keep_files: true`?
- I believe this will ensure that our document builds will never erase the benchmark history.
**Credit**
- https://github.com/rhysd/github-action-benchmark/
**Expect**
Close #104
> Add workflow for benchmark.

- Cargo.toml
- README.md
- examples/rbac_with_domains_policy.csv
- src/adapter/file_adapter.rs
- src/adapter/memory_adapter.rs
- src/adapter/mod.rs
- src/adapter/null_adapter.rs
- src/cached_api.rs
- src/cached_enforcer.rs
- src/core_api.rs
- src/emitter.rs
- src/enforcer.rs
- src/lib.rs
- src/model/assertion.rs
- src/model/function_map.rs
- src/model/mod.rs
- src/prelude.rs
- src/rbac_api.rs
This is a stable version of filtered adapter, I merged both FilteredAdapter and Adapter into one trait because rust is strongly typed and doesn't support dynamic casting.
The disadvantage of this is: this PR will break `diesel-adapter` and `sqlx-adapter`, we will need to implement
```rust
async fn load_filtered_policy(&mut self, m: &mut dyn Model, f: Filter) -> Result<()>;
fn is_filtered(&self) -> bool;
```
for them.
@xcaptain  pls see if you like this better
> Stable filtered adapter

- src/enforcer.rs
- src/util.rs
This PR allows to define in model some thing like this, I would like to solve: https://github.com/casbin/casbin/issues/354
```ini
[request_definition]
r = sub, obj, act
[policy_definition]
p = sub, obj, act
[policy_effect]
e = some(where (p.eft == allow))
[matchers]
m = Any(_) && r.obj == p.obj && r.act == p.act
```
and in policy we can then write like this:
```
p, Any(r.sub.age > 18), /data1, read
```
This policy means that we don't care who is the person sending request, but his/her age should be greater than 18
I made it works in casbin-rs, not sure if we should do like this but I think it may helps solving some problems.
Also can the syntax be better?
> POC try scaling abac rules

- src/adapter/file_adapter.rs
- src/adapter/memory_adapter.rs
- src/adapter/mod.rs
- src/adapter/null_adapter.rs
- src/cached_enforcer.rs
- src/core_api.rs
- src/enforcer.rs
Values of type `&'static str` must be known at compile time. Using a
lifetime of `&'a str` allows use of filter values determined at runtime.
Fixes https://github.com/casbin/casbin-rs/issues/195
> Change Filter definition to support dynamic filter.

- .github/workflows/changelog.yml
- Cargo.toml
- src/cache/default_cache.rs
- async-std 1.7 -> 1.8
- lru-cache -> lru 
The switch to lru is only because it is still actively maintained.
Also, the overlap of partial dependencies may reduce compilation costs and size, albeit to a small degree.
> feat: switch to lru

- Cargo.toml
- src/enforcer.rs
On running ```cargo build```, build was failing - 
```
warning: unused import: `RegisterFn`
--> src/enforcer.rs:34:54
|
34 |     Dynamic, Engine, EvalAltResult, ImmutableString, RegisterFn, Scope,
|                                                      ^^^^^^^^^^
|
= note: `#[warn(unused_imports)]` on by default
warning: use of deprecated trait `rhai::RegisterFn`: this trait is no longer needed and will be removed in the future
--> src/enforcer.rs:34:54
|
34 |     Dynamic, Engine, EvalAltResult, ImmutableString, RegisterFn, Scope,
|                                                      ^^^^^^^^^^
|
= note: `#[warn(deprecated)]` on by default
error[E0599]: no method named `set_fn_1` found for mutable reference `&mut Module` in the current scope
--> src/enforcer.rs:43:9
|
43 | …
```
> bump rhai to 0.19.15

- .github/workflows/pull_request.yml
There is a issue with criterion-benchmark-action. This does not allow comments from PRs from forked repositories. 
ref - https://github.community/t5/GitHub-Actions/quot-Resource-not-accessible-by-integration-quot-for-adding-a/td-p/33925
This will allow comments from PRs inside the repository only.
Signed-off-by: smrpn <samarpan_d@pp.iitr.ac.in>
> feat: add comment for benchmark result

- Cargo.toml
- benches/benchmark.rs
- src/cached_enforcer.rs
- src/core_api.rs
- src/enforcer.rs
- src/macros.rs
- src/model/assertion.rs
- src/model/default_model.rs
- src/model/mod.rs
- src/rbac/default_role_manager.rs
- src/rbac_api.rs
`parking_lot::RwLock` performs better than `std::sync::RwLock` in most benchmarks.
Since `parking_lot` has been indirectly dependent, there is no need to sacrifice compilation time.
> perf: use parking_lot::RwLock

- .github/workflows/ci.yml
- Cargo.toml
- src/adapter/memory_adapter.rs
- src/cached_enforcer.rs
- src/enforcer.rs
- src/model/assertion.rs
- src/model/default_model.rs
In this PR, I use my crate `ritelinked` to replace `indexmap`. In the local test, it will bring a big performance improvement for most benchmarks. Of course, this still needs to be further evaluated.
In addition, a new `amortized` feature is provided. Thanks to `griddle` , although it will slow down the performance, but there is reason to believe that it can reduce the long tail effect.
Signed-off-by: Chojan Shang <psiace@outlook.com>
> feat: switch to ritelinked and provide amortized feature

- Cargo.toml
Steps followed to migrate from rust 2018 to 2021:
1. `cargo update`
2. `cargo fix –-edition`
3. updated the `cargo.toml` --edition
4. ran `cargo build` and `cargo test` to check whether changes are implemented and code is running. The warnings were resolved after the update in the main repository which included the change of syntax of def_package! compatible with latest `rhai` edition
5. Updated the `Cargo.toml` file dependencies to their latest version
6. `cargo +nightly udeps` to check the unused dependencies, found none
7. `cargo outdated` to check outdated dependencies, found some, updated via `cargo update`
8. `cargo build` and `cargo test` to verify the changes are implemented successfully
> fix: Initial migration from Rust 2018 to Rust 2021

- src/rbac_api.rs
For now, `delete_user()` only removes grouping policies:
https://github.com/casbin/casbin-rs/blob/ef5ef67a9257f5864a568ab4eeaae618ab510603/src/rbac_api.rs#L259-L262
But other versions (Golang, Node, Python, etc.) remove both grouping policies and policies, take Golang version for example:
https://github.com/casbin/casbin/blob/cb944fd5ef0a0029b6e74b8ca658f7dcb72e69f9/rbac_api.go#L95-L104
Previous discussion is here ( https://github.com/casbin/node-casbin/issues/118 ) , and participants including @hsluoyz agreed that `delete_user()` should also delete policies, not only grouping policies.
Related PRs:
+ Golang ver: https://github.com/casbin/casbin/pull/364
+ Node ver: https://github.com/casbin/node-casbin/pull/119
PS: I'm a GSoC 2022 candidate and submitted my proposal for `casbin-rs`. I've …
> fix: delete_user() should remove both grouping policies and policies

- Cargo.toml
- src/adapter/file_adapter.rs
- src/rbac/default_role_manager.rs
- src/rbac_api.rs
This relation model is built after the Go implementation, but uses edges inside the graph to model relations instead of having each role store pointers in maps.
Edges with the `EdgeVariant::Link` are relations which in Go are modeled by the `roles` and `users` map.
Edges with the `EdgeVariant::Match` are relations which is Go are modeled by the `matched` and `matchedBy` map.
This change brings significant speedups in benchmarks when compared against the master branch.
> Use petgraph inside DefaultRoleManager to model relations

- src/effector.rs
- src/rbac_api.rs
there are 3 errors when running `cargo clippy -- -D warnings` , I fixed it
> fix: resolve cargo clippy warnings

- src/rbac/default_role_manager.rs
There are many duplicate code in `default_role_manager.rs` , making it hard to understand and maintain code, I improved it by removing duplicate code.
> feat: avoid duplicate code in default_role_manager

- .github/workflows/pull_request.yml
Fix: https://github.com/casbin/casbin-rs/issues/294
I found benchmark workflow doesn’t work well that it fails to post comment to PR.
The reason is `GITHUB_TOKEN` only has read permission to pull requests when access by forked repos, so when a new PR is coming, running workflows only has read-only permission (of course not allowed to post comment). ref: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
Luckily, GitHub has [introduced a new event type: `pull_request_target`](https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/), which allows to run workflows from base branch and pass a token with write permission, so we can use it to post benchmark results to PR (ref: …
> fix: benchmark workflow cannot post comment to PR

- .github/workflows/coverage.yml
- Cargo.toml
- src/adapter/file_adapter.rs
- src/cache/default_cache.rs
- src/cache/mod.rs
- src/cached_api.rs
- src/cached_enforcer.rs
- src/convert.rs
- src/enforcer.rs
- src/macros.rs
- src/rbac/default_role_manager.rs
- src/rbac/role_manager.rs
Replace the `lru` library with `mini-moka` for caching. This allows the API to take `&self` instead of `&mut self` for most operations.
This also allows to only take a read lock when executing `g` functions.
> feat: replace lru with mini-moka for caching

- examples/multi_section_model.conf
- examples/multi_section_policy.csv
- src/cached_enforcer.rs
- src/config.rs
- src/core_api.rs
- src/effector.rs
- src/enforcer.rs
- src/lib.rs
- src/macros.rs
- src/rbac/default_role_manager.rs
Added enforcer context struct + function for enabling multiple section type
P.S.
I'm very new to the community. So, If I do anything wrong, please don't hesitate to tell and correct me.
Thank you
> feat: added enforcer context to enable multiple section type

- .github/workflows/release.yml
> fix: Automatic release failed

- .github/workflows/ci.yml
- Cargo.toml
- src/adapter/memory_adapter.rs
- src/model/assertion.rs
- src/model/default_model.rs
Replaces the dependency on `ritelinked` with the more popular and maintained `hashlink` (of which `ritelinked` was originally just a fork of).  Also removes the `amortized` feature since that applied exclusively to `ritelinked`.
Closes #326
> feat: replace `ritelinked` with `hashlink`

- src/cached_enforcer.rs
- src/core_api.rs
- src/enforcer.rs
- src/model/function_map.rs
Fix: https://github.com/casbin/casbin-rs/issues/337
**API changed:** operator function definition changed due to different signature of `key_get` functions
> feat: add key_get series built-in operator

- Cargo.toml
- src/frontend.rs
- src/lib.rs
- src/model/default_model.rs
- src/model/mod.rs
Fix: https://github.com/casbin/casbin-rs/issues/334
> feat: add casbin_js_get_permission_for_user

- src/enforcer.rs
- src/rbac_api.rs
- resolve: #341 
- feat: remove empty line after doc comments in enforce_with_context to fix warning in cargo-clippy.
> feat: change mut ref to ref in the parameters of get_roles_for_user and other similar functions.

- .github/workflows/coverage.yml
switch to run cargo-tarpaulin by cargo
> feat: fix cargo-tarpaulin run failed issue in CI

- src/cached_enforcer.rs
- src/core_api.rs
- src/effector.rs
- src/enforcer.rs
For: https://github.com/casbin-rs/casbin-rust-cli/issues/5
> feat: add enforce_ex api

- src/convert.rs
- src/enforcer.rs
- src/model/function_map.rs
- Feature  
1. **Added `key_match4` and `key_match5` functions**  
- Implemented new pattern-matching logic for extended policy rule support.  
- Converted inline comments to Rust doc comments (`///`) for improved API documentation.  
2. **Generic implementation for `EnforceArgs`**  
- Refactored `EnforceArgs` implementation from `Vec<String>` to generic `Vec<T>`.  
- Enables compatibility with any vector type while maintaining type safety.
> feat: Implement key_match4/key_match5 functions and generic EnforceArgs<T>

- .github/workflows/release.yml
Auto Release should be triggered after CI
> feat: add condition to CI for auto release

- src/macros.rs
* [`src/macros.rs`](diffhunk://#diff-315c02cd05738da173861537577d159833f70f79cfda8cd7cf1a0d7a28ace31bL83-R83): Changed the condition in the `push_index_if_explain` macro from checking if `cap` is greater than 1 to checking if `cap` is greater than 0.
> fix: fix wrong cap range in push_index_if_explain marco
