casbin/casbin-rs

examples/testini.ini, src/config.rs
Hello, I added the support of parsing config files with multiple lines, could you review the code?
=> [add]: support for parsing config files with multiple lines

Cargo.toml, README.md, src/config.rs, src/enforcer.rs, src/lib.rs, src/management_api.rs, src/model.rs, src/rbac_api.rs
=> Add some get started doc

Cargo.toml, README.md
=> update some metadata

Cargo.toml
Add some keywords and readme and also optimize --release compiles
=> Add some keywords and readme and also optimize --release compiles

Cargo.toml, README.md, src/adapter.rs, src/adapter/file_adapter.rs, src/adapter/memory_adapter.rs, src/cached_enforcer.rs, src/config.rs, src/enforcer.rs, src/internal_api.rs, src/management_api.rs, src/model.rs, src/rbac_api.rs
This PR adds `async/await` support
=> add async/await support

.github/workflows/rustdoc.yml
Now everything has been verified.
Do the following for it to take effect:
- https://github.com/peaceiris/actions-gh-pages#1-add-ssh-deploy-key
- Create `gh-pages` branch
- Run this workflow.
If all goes well, you can see it at http://casbin.github.io/casbin-rs/casbin
If you need https, please turn it on in settings.
=> Build docs

.github/workflows/rustdoc.yml
- Update to peaceiris/actions-gh-pages@v3
- Disable build when have a pull request.
=> Update rustdoc workflow.

src/adapter/file_adapter.rs, src/adapter/memory_adapter.rs, src/adapter/mod.rs, src/enforcer.rs, src/internal_api.rs, src/management_api.rs, src/model/default_model.rs, src/model/mod.rs, src/rbac_api.rs
fix issue#73
Use Vec<String> instead of Vec<&str> to avoid lifetime issue
=> Refactor: modify Vec<&str> to Vec<String> (#73)

src/rbac_api.rs
fix: https://github.com/casbin/casbin/issues/442
=> fix get_implicit_users_for_permission api

src/effector.rs
=> Revert "Fix: CI"

Cargo.toml, README.md, src/effector.rs, src/enforcer.rs, src/error.rs
=> Revert "Effector stream"

Cargo.toml, README.md, src/adapter/file_adapter.rs, src/adapter/memory_adapter.rs, src/cached_enforcer.rs, src/enforcer.rs, src/macros.rs, src/model/assertion.rs, src/model/default_model.rs, src/rbac/default_role_manager.rs, src/rbac_api.rs, src/util.rs
=> Fix unhandled dquote

Cargo.toml, README.md, src/core_api.rs, src/internal_api.rs, src/lib.rs, src/prelude.rs
Signed-off-by: Cheng JIANG <jiang.cheng@vip.163.com>
close: #197
=> feat: re-exports rhai & add IEnforcer && bump version

.github/workflows/changelog.yml, CHANGELOG.md
Usage: No configuration is required, just merge this PR
Behavior: trigger every time push, upload if there is an update.
Close: #205
=> Automatic change log generation.

.github/workflows/changelog.yml, CHANGELOG.md, Cargo.toml, src/convert.rs, src/model/default_model.rs, src/rbac_api.rs
=> upgrade versions of rhai & tokio

.vimspector.json, Cargo.toml, src/adapter/file_adapter.rs, src/util.rs
Signed-off-by: Cheng JIANG <alex_cj96@foxmail.com>
close: #214
=> fix(csv): shouldn't delete inner double quotes

Cargo.toml, src/rbac_api.rs
Signed-off-by: Cheng JIANG <alex_cj96@foxmail.com>
Closes: #221
=> revert tokio upgrade

.github/workflows/ci.yml
try to install gnu tar and add it to github env
work around https://github.com/actions/cache/issues/403
Signed-off-by: Chojan Shang <psiace@outlook.com>
=> ci: using gnu tar

Cargo.toml, README.md
=> Feat: bump version 2.0.7

README.md
=> Fix: fix README.md

Cargo.toml, benches/benchmark.rs
This PR just adds the criterion.rs bench.
Github actions support for criterion will be added in the next PR. This is because benchmark build will fail now, since there is no benchmark stats to compare with in the master branch.
Signed-off-by: smrpn <samarpan_d@pp.iitr.ac.in>
=> feat: Migrate to Criterion benchmark

.github/workflows/pull_request.yml
Signed-off-by: smrpn <samarpan_d@pp.iitr.ac.in>
=> add github actions for benchmark

Cargo.toml
=> Feat: optimize incremental compilation time

.github/workflows/pull_request.yml
=> ci: add bench notice comment

Cargo.toml
=> feat: change default async runtime to tokio

Cargo.toml, src/rbac/default_role_manager.rs, src/util.rs
- bump ip_network and rhai
- try to make clippy happy
Closes: #266 #267
=> build(deps): update ip_network and rhai

src/model/assertion.rs, src/rbac/default_role_manager.rs, src/util.rs
Signed-off-by: smrpn <samarpan_d@pp.iitr.ac.in>
=> ft: remove borrow errors and made Assertion struct fields public

Cargo.toml, README.md
=> feat: bump version 2.0.9

README.md
=>  docs: mention that Enforcer is not thread-safe

src/rbac_api.rs
Signed-off-by: Chojan Shang <psiace@outlook.com>
Fixes: #277
=> fix(clippy): try to make clippy happy

README.md
=> README: link example showing how to preload policy

Cargo.toml, src/enforcer.rs
Signed-off-by: Chojan Shang <psiace@outlook.com>
=> fix: make clippy happy

src/model/function_map.rs
The go implementation uses a replace_all instead of this loop which
avoids the possible endless loop. This PR changes the implementation of keyMatch2 and keyMatch3 to the one similar to the go implementation.
A benchmark with a single parameter `/foo/{bar}/foo` showed no meaningful impact. 15.09 ns to 15.1 ns per iteration.
`/{}` will no be replaced by `/[^/]+` (`/:` accordingly), basically using them as unnamed url parts.
Thus `/{}/bar` will now match `/foo/bar`
Fixes #282
=> fix: possible endless loop when passing /{} or /:/ to keyMatch2 and 3

Cargo.toml, src/enforcer.rs, src/model/function_map.rs, src/util.rs
- change to once_cell from lazy_static.
- bump rhai, and make clippy happy again
=> refactor: change to once_cell

Cargo.toml, src/adapter/mod.rs, src/adapter/string_adapter.rs, src/lib.rs, src/prelude.rs
- feat: String Adapter
- feat: unit test
=> feat: add string adapter

.github/workflows/release.yml
- feat(ci): switch auto release action to semantic-release (https://github.com/casbin-rs/semantic-release-action-rust)
=> feat(ci): switch auto release action to semantic-release
